### ISSUE TITLE
Publish as an NPM package

### ISSUE THREAD

**Issue by mourner** [jahting/pnltri.js#2]
Most JS libraries nowadays are published as NPM packages which makes using them in other projects extremely easy. 

Publishing on NPM is as easy as adding a `package.json` file and running `npm publish`.

**Comment by jahting** [comment]
Done, I hope it works.

**Comment by mourner** [comment]
Hmm, but where your package.json in the repo?

**Comment by jahting** [comment]
Not sure what you mean. When I do `npm install pnltri` I get the following files: `README.md, example.js, package.json, pnltri.js, pnltri.min.js`. What do you miss?

**Comment by mourner** [comment]
No, it's ok, I just expected it to be in the root of the repo :)
